### ISSUE TITLE
Please upload the AppImage to GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [SieloBrowser/SieloBrowser#43]
Please upload the AppImage to GitHub Releases, this would make it much easier to integrate it into the AppImageHub central directory of available AppImages. Thank you.

**Comment by Faymoon** [comment]
Hi,
I think it could be a great idea but we'll wait the Open Beta 10 to do it, (this beta is already done).
I think Feldrise will do it tonight.

**Comment by Feldrise** [comment]
Actually you are write, but I forgot to add open beta 10.x's release... I will release a new version in advance this evening, thank you for the issue!

**Comment by probonopd** [comment]
Unfortunately the AppImage does not run on Ubuntu 14.04 (the currently oldest still-supported LTS release):

```
firejail ./BeingTested.AppImage /run/firejail/appimage/.appimage-7032/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-7032/AppRun)
```

Can you please build on 14.04 or earlier to ensure that the resulting AppImage is compatible with all still-supported LTS releases? Thanks.

Reference:
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems

**Comment by Feldrise** [comment]
OK, I will setup a 14.04 Ubuntu VM and keep the 16.04 one in order to build a Snap package. Thanks for the report!

**Comment by Feldrise** [comment]
Normally the appimage is attached to the last release. I will try build on Ubuntu 14.04 for the next open beta but I first need to check if I can compile with the support of C++17.

**Comment by Feldrise** [comment]
As I said in [issue #62](https://github.com/SieloBrowser/SieloBrowser/issues/62) Sielo can't compile on Ubuntu under 16.04. 

However the app image is now uploaded on GitHub releases as requested, thank you! ^^
