### ISSUE TITLE
compiling on windows?

### ISSUE THREAD

**Issue by echostorm** [SieloBrowser/SieloBrowser#48]
Who here has managed to compile on windows the master version? I tried both ways from Cmake and then trying to build the VS solution + I tried through the Qt Creator IDE but I always end up with huge number of errors and cant compile anyway to go through a step by step tutorial? I only did a few changes to cmakelists that is to change CMAKE_PREFIX_PATH "C:\\Qt\\5.11.0\\msvc2017_64\\" for windows 64bit cmake shows no problems and I did use same ndb and mpl library as what is in the repository...

**Comment by Feldrise** [comment]
Hmm. First ensure to clone the latest version of Master branch since I fixed pot of issues yesterday in the evening.
Also, since ndb is a submodule and have submodule, you must have the flag `recurse-submodules`.

If it still not working, please can you send errors in the output?

**Comment by echostorm** [comment]
I only managed to compile the taged reposortry :Sielo version 1.14.00b with
QtWebEngine version 5.11.0 and working fine but master branch could not! still will try a little more with it if all fails ill send output...

**Comment by echostorm** [comment]
first trying to git with recurse-submodules doesnt work any more cause it cant find ndb however I manually added it so that's not an issue once I do cmake for visual studio project VS2017 64bit I get following output from cmake:

```
> Selecting Windows SDK version 10.0.15063.0 to target Windows 6.1.7601.
> The C compiler identification is MSVC 19.10.25019.0
> The CXX compiler identification is MSVC 19.10.25019.0
> Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
> Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
> Detecting C compiler ABI info
> Detecting C compiler ABI info - done
> Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
> Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
> Detecting CXX compiler ABI info
> Detecting CXX compiler ABI info - done
> Detecting CXX compile features
> Detecting CXX compile features - done
> --------------------------------------------------------
>                          NDB
> --------------------------------------------------------
> SQLITE : ON
> MONGO : OFF
> MYSQL : OFF
> BUILD_EXP : OFF
> BUILD_TEST : OFF
> BUILD_EXAMPLE : OFF
> Found OpenSSL: D:/Sielo-Master/third-party/openssl/windows/x64/lib/libcrypto.lib (found suitable version "1.1.0g", minimum required is "1.1.0") 
> Configuring done
> Generating done
```

after that I tried opening in VS and building following is entire output:
[VS2017_output.txt](https://github.com/SieloBrowser/SieloBrowser/files/2046242/VS2017_output.txt)
it seems still some problem related to ndb right?

**Comment by echostorm** [comment]
error output in excel table format:
[errors.xlsx](https://github.com/SieloBrowser/SieloBrowser/files/2046268/errors.xlsx)

**Comment by Feldrise** [comment]
Now it should be fixed :wink:
