### ISSUE TITLE
AppImage does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [SieloBrowser/SieloBrowser#62]
The AppImage does not run on Ubuntu 14.04 which currently is the oldest still-supported distribution: `AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'CXXABI_1.3.9' not found `

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems and especially https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6.

References:
* https://github.com/AppImage/appimage.github.io/pull/552
* https://travis-ci.org/AppImage/appimage.github.io/builds/398998404#L618

**Comment by Feldrise** [comment]
Well, since Sielo event not build on Ubuntu 14.04 beceause it use C++17, I'll not support Ubuntu below the 16.04 :smile:

Thank you!

**Comment by probonopd** [comment]
Thanks for the clarification @Feldrise. Is it a good idea to depend on C++17 already when there are still plenty of still-supported distributions out there that do not support it? This means that you are essentially cutting off users running on otherwise still-supported distributions from using Sielo.

**Comment by Feldrise** [comment]
I don't really have the choice since I'm using [ndb](https://github.com/ads00/ndb).

It's true that it's make Sielo not available on some distribution, but now it's not always hard to have at least GCC 7 or clang 5.

Sielo is still available on most Linux distribution though :wink:
