### ISSUE TITLE
Pour l'open-source

### ISSUE THREAD

**Issue by ValentinGratz** [SieloBrowser/SieloBrowser#71]
le titre : pour parler non pas du navigateur, mais du site

donc je propose l'idée de pouvoir faire un catalogue de thème et d'extensions, ainsi qu'une page avec des tuto pour comment développer une extension ou un thème et le partager.

**Comment by Feldrise** [comment]
C'est très intéressant, mais ça pourrait plutôt passer sur le repository du site lui même : https://github.com/SieloBrowser/SieloWebsite :wink:

**Comment by ValentinGratz** [comment]
Désolé, je ne le savait pas, tu veux que je le reposte sur le github du site ou pas vraiment ?

**Comment by Feldrise** [comment]
Oui bien sur ça sera d'autant plus intéressant et Kaktus pourra réagir, je ne suis pas en charge du site 😛
