### ISSUE TITLE
Barre de navigation sur le navigateur

### ISSUE THREAD

**Issue by ValentinGratz** [SieloBrowser/SieloBrowser#72]
Sur la barre de saisie d'adresse, on ne voit rien pour revenir en arrière, arrêter le chargement de la page.

J'ai vu dans les options avancés que l'on pouvait mettre cela, mais pour celui qui ne connait pas très bien et qui ne veut pas allé dans les options avancés, ce serait bien de le mettre par défaut.

**Comment by Feldrise** [comment]
Par défaut tu es censé avoir le choix dès le début entre le bouton flottant et la barre d'outil. Peut-être qu'il serait intéressant de prioriser la barre d'outil au bouton flottant ? J'invite tout le monde a réagir avec un :+1: si vous êtes favorable a la barre d'outil par défaut et :-1: si vous êtes favorable au bouton flottant par défaut
(à noter que ça n'aura de conséquence que pour ceux qui valident sans lire les premiers dialogs)

**Comment by Feldrise** [comment]
La version 1.18 simplifie grandement tout cela et clarifie le choix du bouton flottant 😉 

![Sielo 1.18.00](https://cdn.discordapp.com/attachments/431827990561947649/531148557416398848/unknown.png)
