### ISSUE TITLE
La page de configuration

### ISSUE THREAD

**Issue by ValentinGratz** [SieloBrowser/SieloBrowser#74]
Ce qui serait bien est en configuration par défaut n'avoir qu'une seule fois la page de configuration du navigateur. 

Car à la longue, si a chaque fois faut reconfigurer, on a tendance a passer a un autre navigateur

**Comment by Feldrise** [comment]
Ce problème n'est toujours pas corrigé ? J'aimerais que tu m'envoies un Zip de ton dossier "profiles" dans `C:\Users\toi\AppData\Local\Sielo` (à noter que `AppData` est un dossier cacher)

Tu es bien la seul personne qui me signal ce problème 😅

**Comment by Feldrise** [comment]
OK, je viens de comprendre ton problème par rapport à notre discussion sur Discord.
Je dois changer légèrement l'URL de la page d'accueil de Sielo, je place cette issue dans ToDo pour le prochain patch de la 1.17 😉

**Comment by Feldrise** [comment]
Corrigé dans ce commit : https://github.com/SieloBrowser/SieloBrowser/commit/6b990b115f209a5f41d559d3a1501d80b1297fd0
