### ISSUE TITLE
menu sidebar vide

### ISSUE THREAD

**Issue by ValentinGratz** [SieloBrowser/SieloBrowser#81]
Dans le menu vue > SideBar qui indique un autre menu, hors ce menu n'existe pas Est-ce normal ? 

![no menu](https://user-images.githubusercontent.com/39189263/50520380-50f8ec00-0ac0-11e9-841c-9417dc1cc070.png)

**Comment by Feldrise** [comment]
Ce menu est réservé pour les plugins. Si tu actives certain plugin tu devrais voir des sidebar apparaîtres 😉
