### ISSUE TITLE
Changer de place la barre des favoris

### ISSUE THREAD

**Issue by ValentinGratz** [SieloBrowser/SieloBrowser#83]
Avoir la possibilité de changer de place la barre de favoris facilement.

Pour le moment, c'est un peu comme ci je voulais changer la barre d'outils de place de Windows, ce qui n'est pas facile
![changer de place la barre des favoris](https://user-images.githubusercontent.com/39189263/50520470-e4322180-0ac0-11e9-88d3-ad98d2b52038.png)

**Comment by ValentinGratz** [comment]
Quand j'essaye, c'est un peu comme la barre des tâches que j'ai eu le tour voici ce que j'ai 
![pb barre favoris deplacement](https://user-images.githubusercontent.com/39189263/50541739-03f24400-0bac-11e9-9236-d7431d8f6548.png)

**Comment by Feldrise** [comment]
La version 1.18 apporte des améliorations niveau interface, notamment la barre de favoris qui passe en dessous de la barre de titre et n'est plus présente par défaut :D 

![Sielo 1.18.00](https://cdn.discordapp.com/attachments/431827990561947649/531148557416398848/unknown.png)
