### ISSUE TITLE
Arch Linux AUR package is broken: Cannot download source.

### ISSUE THREAD

**Issue by dreirund** [SieloBrowser/SieloBrowser#91]
Since "you" seem also to take care of [the Arch Linux AUR package](https://aur.archlinux.org/packages/sielo-navigateur/) for Silo, I post the issue here:

It points to the source [http://feldrise.com/Sielo/Linux/sielo-navigateur-v0.4.0.tar.gz](http://feldrise.com/Sielo/Linux/sielo-navigateur-v0.4.0.tar.gz). This cannot be downloaded (HTTP error 404 "not found"). Also changing this to the up to date stable release 1.17.14: [http://feldrise.com/Sielo/Linux/sielo-navigateur-v1.17.14.tar.gz](http://feldrise.com/Sielo/Linux/sielo-navigateur-v1.17.14.tar.gz) gives an HTTP error "404 not found".

The `PKGBUILD` should be changed to point to from [https://github.com/SieloBrowser/sielo-legacy/archive/v${pkgver}.zip](https://github.com/SieloBrowser/sielo-legacy/archive/v1.17.14.zip). Maybe the `package()`-function also needs adaption.

On the other hand, you could consider making a `sielo-navigateur-git`-package as well which always checks out the latest state from the git repository.

**Comment by Feldrise** [comment]
It's because you are seeing a very, very old package. "Sielo navigateur" has been renamed "Sielo browser" in English (because "Navigateur" is the french word for "Browser").

Knowing that you can see a new world 😁 
> Here's the main package: https://aur.archlinux.org/packages/sielo-browser/
> Here's the git-based package: https://aur.archlinux.org/packages/sielo-browser-git/ 

Hope this will help 😉

**Comment by dreirund** [comment]
> It's because you are seeing a very, very old package. "Sielo navigateur" has been renamed "Sielo browser" in English (because "Navigateur" is the french word for "Browser").
> 
> > Here's the main package: https://aur.archlinux.org/packages/sielo-browser/
> > Here's the git-based package: https://aur.archlinux.org/packages/sielo-browser-git/

Then please make sure the old package get's deleted & post a comment to the AUR of the outdated package.

**Comment by Feldrise** [comment]
I which but I don't know how. I can't even know where to accept you request to delete it 😅

EDIT: now I can even post a comment, I'll try again on my computer 😂

**Comment by dreirund** [comment]
On Sat, 31 Aug 2019 01:11:30 -0700, Feldrise <notifications@github.com>
wrote about "Re: [SieloBrowser/sielo-legacy] Arch Linux AUR package is
broken: Cannot download source. (#91)":

> I which but I don't know how. I can't even know where to accept you
> request to delete it 😅

You submit a deletion request, and the AUR admins will take care of it.

I did submit it because you did not originally, when you already knew
that the pakage has been superseeded.

**Comment by Feldrise** [comment]
Ok, thank you very much I did not know about that before 😉
